/*******************************************************************************
* FILE NAME: PgHndler.cpp                                                      *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     APageHandler- Notebook page handler                                      *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _APAGEHANDLER_
#include "PgHndler.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (APageHandler::readyId)
const INotificationId APageHandler::readyId = "APageHandler::readyId";

//------------------------------------------------------------------------------
// APageHandler :: APageHandler
//------------------------------------------------------------------------------
#pragma export (APageHandler::APageHandler())
APageHandler::APageHandler()
{

   initialize();
}     //end constructor


//------------------------------------------------------------------------------
// APageHandler :: ~APageHandler
//------------------------------------------------------------------------------
#pragma export (APageHandler::~APageHandler())
APageHandler::~APageHandler()
{

}

//------------------------------------------------------------------------------
// APageHandler :: initializePart
//------------------------------------------------------------------------------
#pragma export (APageHandler::initializePart())
APageHandler & APageHandler::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// APageHandler :: makeConnections
//------------------------------------------------------------------------------
#pragma export (APageHandler::makeConnections())
Boolean APageHandler::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "PgHndler.cpv"
