/*******************************************************************************
* FILE NAME: PgHndler.hpp                                                      *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     APageHandler- Notebook page handler                                      *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _APAGEHANDLER_
#define _APAGEHANDLER_  

class APageHandler;

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _IPAGEHDR_
#include <ipagehdr.hpp>
#endif

#ifndef _IPAGEEVT_
#include <ipageevt.hpp>
#endif

#ifndef _INOTEBK_
#include <inotebk.hpp>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif

#include "PgHndler.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for APageHandler
//*****************************************************************************
class APageHandler : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   APageHandler();

   virtual  ~APageHandler();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   virtual APageHandler & initializePart();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:

#include "PgHndler.hpv"
};   //APageHandler


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
