/*******************************************************************************
* FILE NAME: test.h                                                            *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     test                                                                     *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_test
#define WND_test  VBBASEWINDOWID
#endif

#define WNDOFFSET_test_FrameWindow  0
#define WND_test_FrameWindow  WND_test

#define WND_test_Canvas  IC_FRAME_CLIENT_ID

#define WNDOFFSET_test_Notebook1  1
#define WND_test_Notebook1  WND_test + WNDOFFSET_test_Notebook1


#define WNDOFFSET_test_Canvas2  2
#define WND_test_Canvas2  WND_test + WNDOFFSET_test_Canvas2

#define WNDOFFSET_test_EntryField4  3
#define WND_test_EntryField4  WND_test + WNDOFFSET_test_EntryField4


#define WNDOFFSET_test_Canvas1  4
#define WND_test_Canvas1  WND_test + WNDOFFSET_test_Canvas1

#define WNDOFFSET_test_EntryField5  5
#define WND_test_EntryField5  WND_test + WNDOFFSET_test_EntryField5


#define WNDOFFSET_test_Canvas3  6
#define WND_test_Canvas3  WND_test + WNDOFFSET_test_Canvas3

#define WNDOFFSET_test_EntryField3  7
#define WND_test_EntryField3  WND_test + WNDOFFSET_test_EntryField3

#define WNDOFFSET_test_EntryField1  8
#define WND_test_EntryField1  WND_test + WNDOFFSET_test_EntryField1

#define WNDOFFSET_test_PushButton1  9
#define WND_test_PushButton1  WND_test + WNDOFFSET_test_PushButton1

#define WNDOFFSET_test_PushButton2  10
#define WND_test_PushButton2  WND_test + WNDOFFSET_test_PushButton2

#define WNDOFFSET_test_EntryField2  11
#define WND_test_EntryField2  WND_test + WNDOFFSET_test_EntryField2

#define WNDOFFSET_test_StaticText1  12
#define WND_test_StaticText1  WND_test + WNDOFFSET_test_StaticText1

#define WNDOFFSET_test_StaticText2  13
#define WND_test_StaticText2  WND_test + WNDOFFSET_test_StaticText2

#define WNDOFFSET_test_EntryField6  14
#define WND_test_EntryField6  WND_test + WNDOFFSET_test_EntryField6



