/*******************************************************************************
* FILE NAME: test.hpp                                                          *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     test                                                                     *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _TEST_
#define _TEST_  

class test;

#ifndef _IFRAME_
#include <iframe.hpp>
#endif

class ICanvas;
class INotebook;
class IVBNotebookPage;
class IEntryField;
class IPushButton;
class IStaticText;
class APageHandler;
#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

#ifndef _IEVTDATA_
#include <ievtdata.hpp>
#endif

class testConn0;
class testConn2;
class testConn4;
class testConn6;
class testConn8;
class testConn10;
class testConn11;
class testConn12;
#include "test.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for test
//*****************************************************************************
class test : public IFrameWindow {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   test(
      unsigned long id = WND_test,
      IWindow* parent = IWindow::desktopWindow(),
      IWindow* owner = 0,
      const IRectangle& rect = defaultFramingSpec(),
      const IFrameWindow::Style& style = IFrameWindow::defaultStyle ( ),
      const char* title = defaultTitle());

   virtual  ~test();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static IString defaultTitle();
   virtual test & initializePart();
   test * getFrameWindow() { return this; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   ICanvas * iCanvas;
   INotebook * iNotebook1;
   IVBNotebookPage * iVBNotebookPage;
   ICanvas * iCanvas2;
   IEntryField * iEntryField4;
   IVBNotebookPage * iVBNotebookPage1;
   ICanvas * iCanvas1;
   IEntryField * iEntryField5;
   IVBNotebookPage * iVBNotebookPage2;
   ICanvas * iCanvas3;
   IEntryField * iEntryField3;
   IEntryField * iEntryField1;
   IPushButton * iPushButton1;
   IPushButton * iPushButton2;
   IEntryField * iEntryField2;
   IStaticText * iStaticText1;
   IStaticText * iStaticText2;
   IEntryField * iEntryField6;
   APageHandler * iAPageHandler1;
   testConn0 * conn0;
   testConn2 * conn2;
   testConn4 * conn4;
   testConn6 * conn6;
   testConn8 * conn8;
   testConn10 * conn10;
   testConn11 * conn11;
   testConn12 * conn12;
   static unsigned long partWindowId;

friend class testConn12;

};   //test


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
